### ISSUE TITLE
History Command

### ISSUE THREAD

**Issue by Skunkmeister** [DevLUp-Inc/Feedback#13]
**Describe the solution you'd like**
Discord users need to be able to see the history of their posts in a convenient manner to identify holes for retroactive showoff. This eventually can exist in the website.

**Describe alternatives you've considered**
This feature belongs in the site! However its' presence on the bot is... convenient. Maybe. This is a low priority / questionable feature.

**Additional context**
/history [days] would return

                 M  T  W   R   F    S   S
 10/16/22 ✅✅✅❌❌✅❌ 10/22/22
 10/9/22   ✅✅❌❌❌✅✅ 10/15/22
 10/16/22 ✅✅❌✅❌✅❌ 10/22/22
 10/16/22 ✅✅✅❌❌✅❌ 10/22/22
 10/16/22 ✅✅✅❌❌✅❌ 10/22/22
 
 something like this...

**Comment by Exanite** [comment]
Since retroactive showoff has been removed, this isn't an essential feature anymore, but is still something that would look cool.

Also if implemented, this probably should be merged into /streak.

**Comment by Exanite** [comment]
Implemented by adding the requested functionality into the /streak command.
