### ISSUE TITLE
Frontend Account Linking

### ISSUE THREAD

**Issue by Skunkmeister** [DevLUp-Inc/Feedback#19]
Tasks:
- [x] Mutation request
- [x] Open Discord OAuth page
- [x] Redirect to new account-link callback page
- [x] Get code and call link account endpoint (only if logged in and has code)
- [x] Create link account button
- [x] Button should only be clickable when logged in
- [x] Dedicated link account page

**Comment by Exanite** [comment]
Steps:
- [ ] Open discord authorization page
- [ ] Redirect to new account-link callback page
- [ ] Get code and call link account endpoint

- [ ] Create link account button
- [ ] Button should only be clickable when logged in
- [ ] Dedicated link account page
