### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Exanite** [DevLUp-Inc/Feedback#26]
Don't do ~~fancy~~ data stuff yet Michael, we just need a functioning home page at the moment

**Comment by Exanite** [comment]
When you do implement data stuff though, I'll teach you how SSR and SSG works in Next.js

**Comment by Skunkmeister** [comment]
> Don't do fancy data stuff yet Michael, we just need a functioning home page at the moment

yessir, going to populate with pretend data for now as suggested

**Comment by Exanite** [comment]
Bump
