### ISSUE TITLE
Add content to markdown rendered pages

### ISSUE THREAD

**Issue by Exanite** [DevLUp-Inc/Feedback#36]
All of the pages in this repo require proper content to be written.
Since this isn't in GDA.js, this can be done by any anyone: https://github.com/UF-GDA/Website-Content

**Comment by Skunkmeister** [comment]
@Aerohood I figured this might be the sort of thing you could do (if you're up to it). Otherwise I could work on it...
The idea is to just add some content to some of our website's unfinished pages

**Comment by Exanite** [comment]
The website is here if you want to see your changes: https://devlup.org/
