### ISSUE TITLE
Add markdoc highlighting / make editing aesthetic

### ISSUE THREAD

**Issue by Skunkmeister** [DevLUp-Inc/Feedback#46]
![image](https://user-images.githubusercontent.com/4400062/179046476-64e09075-26ca-4079-8a73-303743d4738d.png)

Task tracker:
- [x] Change CodeBlock to use CodeMirror
- [x] Add better mobile support (ability to tab between editor and preview)
- [x] Change project editing page to use CodeMirror

**Comment by Exanite** [comment]
Might be able to use the AST generated by Markdoc for this if we are going for a custom implementation

**Comment by Exanite** [comment]
Can also embed VS Code

**Comment by Exanite** [comment]
Implementing with CodeMirror instead of VS Code/Monaco since it has much better mobile support.

![image](https://user-images.githubusercontent.com/42710136/182933914-74ad8a48-025b-41b1-9c1b-0faea4504bc1.png)
